package executor

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// BuildMCPConfig wires BuildMCPExecutor to its slave-side dependencies.
type BuildMCPConfig struct {
	WorkDir   string                          // slave's cwd; generated_mcp/ + dynamic_mcp.yaml live here
	ClaudeBin string                          // path to claude CLI (or fake during tests)
	MCPExec   *MCPExecutor                    // for RegisterStdio after a successful build
	Republish func(ctx context.Context) error // tunnel.PublishCard hook; called after successful register
}

type BuildMCPExecutor struct {
	cfg BuildMCPConfig

	// Exposed for tests.
	MCPExec *MCPExecutor
}

func NewBuildMCPExecutor(cfg BuildMCPConfig) *BuildMCPExecutor {
	return &BuildMCPExecutor{cfg: cfg, MCPExec: cfg.MCPExec}
}

type buildSpec struct {
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Tools             []buildToolSpec `json:"tools"`
	Hints             string          `json:"hints"`
	AllowedPackages   []string        `json:"allowed_packages"`
	ComposeServers    []string        `json:"compose_servers"`
	Version           int             `json:"version"`
	PriorPath         string          `json:"prior_path"`
	PatchInstructions string          `json:"patch_instructions"`
	Iteration         int             `json:"iteration"`
	MaxIterations     int             `json:"max_iterations"`
}

type buildToolSpec struct {
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	ArgsSchema        json.RawMessage `json:"args_schema"`
	ResultDescription string          `json:"result_description"`
}

var validName = regexp.MustCompile(`^[a-z][a-z0-9_]{0,31}$`)

func (e *BuildMCPExecutor) Run(ctx context.Context, t Task, sink Sink) (Result, error) {
	defer sink.Close()
	var spec buildSpec
	if err := json.Unmarshal([]byte(t.Prompt), &spec); err != nil {
		return Result{}, fmt.Errorf("buildmcp: malformed spec: %w", err)
	}
	if !validName.MatchString(spec.Name) {
		return Result{}, fmt.Errorf("buildmcp: invalid name %q (must match [a-z][a-z0-9_]{0,31})", spec.Name)
	}
	if len(spec.Tools) == 0 {
		return Result{}, fmt.Errorf("buildmcp: spec.tools must have at least 1 entry")
	}
	if spec.Version < 1 {
		return Result{}, fmt.Errorf("buildmcp: spec.version must be >=1")
	}
	if spec.Version >= 2 && spec.PriorPath == "" {
		return Result{}, fmt.Errorf("buildmcp: prior_path required for version>=2")
	}

	specHash := computeSpecHash(spec)

	// Idempotency: if dynamic_mcp.yaml has a matching entry that points at an
	// existing file, short-circuit.
	if existing, ok := e.lookupExistingEntry(spec.Name); ok && existing.SpecHash == specHash && existing.Version == spec.Version {
		if _, err := os.Stat(filepath.Join(e.cfg.WorkDir, existing.Args[0])); err == nil {
			return Result{Summary: e.successHandle(spec, existing.Args[0], existing.Tools, 0).Marshal()}, nil
		}
	}

	priorCode := ""
	if spec.PriorPath != "" {
		b, err := os.ReadFile(filepath.Join(e.cfg.WorkDir, spec.PriorPath))
		if err != nil {
			return Result{}, fmt.Errorf("buildmcp: read prior_path: %w", err)
		}
		priorCode = string(b)
	}

	src, err := e.invokeClaude(ctx, spec, priorCode)
	if err != nil {
		return Result{Summary: blockedHandle(spec, "", "", "claude_invocation", err.Error())}, nil
	}
	src = stripFencesAndJunk(src)

	// Validate syntax.
	if err := validatePythonSyntax(src); err != nil {
		return Result{Summary: blockedHandle(spec, "", "", "validate_syntax", err.Error())}, nil
	}
	// Validate imports.
	bad, _ := ValidateImports(src, spec.AllowedPackages)
	if len(bad) > 0 {
		return Result{Summary: blockedHandle(spec, strings.Join(bad, ","),
			"claude used "+strings.Join(bad, ", ")+" not in allowed_packages",
			"validate_imports", "")}, nil
	}
	// Write file with header.
	relPath := filepath.Join("generated_mcp", spec.Name, fmt.Sprintf("v%d.py", spec.Version))
	absPath := filepath.Join(e.cfg.WorkDir, relPath)
	if err := os.MkdirAll(filepath.Dir(absPath), 0o755); err != nil {
		return Result{}, err
	}
	header := fmt.Sprintf(`# -*- coding: utf-8 -*-
# AUTO-GENERATED by multi-agent build_mcp at %s
# spec.name=%s  version=%d  iteration=%d
# spec_hash=sha256:%s  prior_path=%s
# DO NOT HAND-EDIT. To evolve this file, send another build_mcp task
# with version=N+1, prior_path=this file path, and patch_instructions=...
#
# This file is reserved for framework-generated MCP servers.
# Hand-written MCP servers belong elsewhere (referenced via config.yaml).

`, time.Now().UTC().Format(time.RFC3339), spec.Name, spec.Version, spec.Iteration, specHash, spec.PriorPath)
	full := []byte(header + src)
	if err := os.WriteFile(absPath, full, 0o644); err != nil {
		return Result{}, err
	}
	// Smoke launch.
	tools, err := SmokeLaunchPython(ctx, absPath, 3*time.Second)
	if err != nil {
		_ = os.Remove(absPath)
		return Result{Summary: blockedHandle(spec, "", err.Error(), "smoke_launch", "")}, nil
	}
	// Register.
	mcpCfg := MCPServerCfg{Transport: "stdio", Command: "python3", Args: []string{absPath}}
	if err := e.cfg.MCPExec.RegisterStdio(spec.Name, mcpCfg); err != nil {
		return Result{}, fmt.Errorf("buildmcp: register: %w", err)
	}
	// Persist to dynamic_mcp.yaml.
	if err := e.upsertDynamicYAML(dynamicEntry{
		Name: spec.Name, Transport: "stdio", Command: "python3",
		Args: []string{relPath}, Version: spec.Version,
		CreatedAt: time.Now().UTC().Format(time.RFC3339),
		SpecHash:  specHash, Tools: tools,
	}); err != nil {
		return Result{}, fmt.Errorf("buildmcp: persist yaml: %w", err)
	}
	// Re-publish card.
	if e.cfg.Republish != nil {
		if err := e.cfg.Republish(ctx); err != nil {
			sink.Write("warn", fmt.Sprintf("republish card: %v", err))
		}
	}
	return Result{Summary: e.successHandle(spec, relPath, tools, len(strings.Split(src, "\n"))).Marshal()}, nil
}

func (e *BuildMCPExecutor) successHandle(spec buildSpec, relPath string, tools []string, lineCount int) handleJSON {
	return handleJSON{
		Type: "mcp_tool_set",
		URL:  "file://" + filepath.Join(e.cfg.WorkDir, relPath),
		Meta: map[string]string{
			"name":      spec.Name,
			"version":   strconv.Itoa(spec.Version),
			"tools":     strings.Join(tools, ","),
			"slave_id":  os.Getenv("SLAVE_SANDBOX_ID"),
			"lines":     strconv.Itoa(lineCount),
			"deps":      strings.Join(spec.AllowedPackages, ","),
			"iteration": strconv.Itoa(spec.Iteration),
		},
	}
}

func blockedHandle(spec buildSpec, neededPackages, reason, stage, claudeErr string) string {
	if reason == "" && claudeErr != "" {
		reason = claudeErr
	}
	if len(reason) > 200 {
		reason = reason[:200]
	}
	h := handleJSON{
		Type: "build_mcp_blocked",
		URL:  "",
		Meta: map[string]string{
			"spec_name":       spec.Name,
			"iteration":       strconv.Itoa(spec.Iteration),
			"needed_packages": neededPackages,
			"reason":          reason,
			"stage":           stage,
		},
	}
	return h.Marshal()
}

// handleJSON is a local mirror of pkg/transport.Handle to avoid an import cycle
// between internal/executor and pkg/transport. Field names match.
type handleJSON struct {
	Type  string            `json:"type"`
	URL   string            `json:"url"`
	Bytes int64             `json:"bytes,omitempty"`
	MIME  string            `json:"mime,omitempty"`
	Meta  map[string]string `json:"meta,omitempty"`
}

func (h handleJSON) Marshal() string {
	b, _ := json.Marshal(h)
	return string(b)
}

func (e *BuildMCPExecutor) invokeClaude(ctx context.Context, spec buildSpec, priorCode string) (string, error) {
	args := []string{"--print", "--output-format=stream-json", "--verbose"}
	cmd := exec.CommandContext(ctx, e.cfg.ClaudeBin, args...)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return "", err
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return "", err
	}
	var stderrBuf strings.Builder
	cmd.Stderr = &stderrBuf
	if err := cmd.Start(); err != nil {
		return "", err
	}
	go func() {
		defer stdin.Close()
		io.WriteString(stdin, buildSystemPrompt+"\n\n")
		io.WriteString(stdin, "SPEC:\n")
		b, _ := json.MarshalIndent(spec, "", "  ")
		io.WriteString(stdin, string(b))
		if priorCode != "" {
			io.WriteString(stdin, "\n\nPRIOR CODE (revise according to patch_instructions):\n")
			io.WriteString(stdin, priorCode)
		}
		io.WriteString(stdin, "\n\nRespond with python source only. No markdown, no commentary.")
	}()
	var assembled strings.Builder
	sc := bufio.NewScanner(stdout)
	sc.Buffer(make([]byte, 0, 1<<16), 1<<24)
	for sc.Scan() {
		var msg struct {
			Type    string `json:"type"`
			Message struct {
				Content []struct {
					Type string `json:"type"`
					Text string `json:"text"`
				} `json:"content"`
			} `json:"message"`
		}
		if err := json.Unmarshal(sc.Bytes(), &msg); err != nil {
			continue
		}
		if msg.Type != "assistant" {
			continue
		}
		for _, c := range msg.Message.Content {
			if c.Type == "text" {
				assembled.WriteString(c.Text)
			}
		}
	}
	if err := cmd.Wait(); err != nil {
		return "", fmt.Errorf("claude exit: %v: %s", err, stderrBuf.String())
	}
	return assembled.String(), nil
}

const buildSystemPrompt = `You are generating a Python MCP (Model Context Protocol) stdio server.
Wire format:
- Read JSON-RPC requests one per line on stdin: {"jsonrpc":"2.0","id":<int>,"method":"tools/list" | "tools/call","params":{...}}
- Write JSON responses one per line to stdout: {"jsonrpc":"2.0","id":<int>,"result":{...}} or {"jsonrpc":"2.0","id":<int>,"error":{"message":"..."}}
- For "tools/list" return {"result":{"tools":[{"name":"X"},...]}}
- For "tools/call" with params {"name":"X","arguments":{...}}, dispatch on name; return {"result":{"result":<your value>,"capability_changed":false}}
- Flush after every response.

Constraints:
- Output ONLY a complete Python file. No markdown fences. No commentary. No explanation.
- The file must be a runnable program (use 'if __name__ == "__main__":' guard).
- Limit imports to the packages declared in the spec's allowed_packages plus the Python standard library.
`

func stripFencesAndJunk(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "```") {
		if i := strings.Index(s, "\n"); i > 0 {
			s = s[i+1:]
		}
		s = strings.TrimSuffix(s, "```")
		s = strings.TrimSuffix(s, "```\n")
	}
	return strings.TrimSpace(s) + "\n"
}

func validatePythonSyntax(src string) error {
	cmd := exec.Command("python3", "-c", "import ast,sys; ast.parse(sys.stdin.read())")
	cmd.Stdin = strings.NewReader(src)
	var errBuf bytes.Buffer
	cmd.Stderr = &errBuf
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("ast.parse failed: %v: %s", err, errBuf.String())
	}
	return nil
}

func computeSpecHash(spec buildSpec) string {
	b, _ := json.Marshal(spec)
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

type dynamicEntry struct {
	Name      string   `yaml:"-"`
	Transport string   `yaml:"transport"`
	Command   string   `yaml:"command"`
	Args      []string `yaml:"args"`
	Version   int      `yaml:"version"`
	CreatedAt string   `yaml:"created_at"`
	SpecHash  string   `yaml:"spec_hash"`
	Tools     []string `yaml:"tools,omitempty"`
}

type dynamicFile struct {
	Servers map[string]dynamicEntry `yaml:"servers"`
}

func (e *BuildMCPExecutor) yamlPath() string {
	return filepath.Join(e.cfg.WorkDir, "dynamic_mcp.yaml")
}

func (e *BuildMCPExecutor) lookupExistingEntry(name string) (dynamicEntry, bool) {
	df, err := e.readDynamicYAML()
	if err != nil {
		return dynamicEntry{}, false
	}
	d, ok := df.Servers[name]
	return d, ok
}

func (e *BuildMCPExecutor) readDynamicYAML() (dynamicFile, error) {
	b, err := os.ReadFile(e.yamlPath())
	if err != nil {
		if os.IsNotExist(err) {
			return dynamicFile{Servers: map[string]dynamicEntry{}}, nil
		}
		return dynamicFile{}, err
	}
	var df dynamicFile
	if err := yaml.Unmarshal(b, &df); err != nil {
		return dynamicFile{}, err
	}
	if df.Servers == nil {
		df.Servers = map[string]dynamicEntry{}
	}
	return df, nil
}

func (e *BuildMCPExecutor) upsertDynamicYAML(entry dynamicEntry) error {
	df, err := e.readDynamicYAML()
	if err != nil {
		return err
	}
	df.Servers[entry.Name] = entry
	out, err := yaml.Marshal(df)
	if err != nil {
		return err
	}
	tmp := e.yamlPath() + ".tmp"
	if err := os.WriteFile(tmp, out, 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, e.yamlPath())
}
