#!/usr/bin/env python3
"""Emit a self-contained bash payload that runs mcp_acceptance.py on a slave.

Solves the "I need to ship the runner + cases.jsonl + (maybe) the server
source to the slave, then run acceptance, then clean up, then surface the
exit code" problem. Output is a single bash script ready to pass to the
driver's `run_slave_bash` MCP tool as its `script` parameter.

Files are embedded as base64 so there is no quoting/escaping risk.

Usage:
    python3 remote_run.py \\
        --cases cases.jsonl \\
        --server-cmd "python3 /tmp/mcpa/server.py" \\
        --source generated_mcp/foo/v1.py:/tmp/mcpa/server.py \\
        > /tmp/payload.sh

Then in driver Claude:
    run_slave_bash(target_display_name="slave-a", script=<content of payload>)

Exit code propagation: the generated script exits with whatever
mcp_acceptance.py returned (0 pass / 1 case failed / 2 handshake failed).
Cleanup is best-effort and runs in a trap so partial failures still clean up.
"""
from __future__ import annotations

import argparse
import base64
import os
import sys
from pathlib import Path


# By default we co-locate with the canonical runner. Override with --runner
# if you've checked out a different copy.
DEFAULT_RUNNER = Path(__file__).resolve().parent / "mcp_acceptance.py"


def b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def parse_source(spec: str) -> tuple[Path, str]:
    """Parse SRC:DEST. DEST is the absolute path on the slave."""
    if ":" not in spec:
        raise SystemExit(
            f"--source expects SRC:DEST (got {spec!r}); "
            "DEST must be an absolute path on the slave"
        )
    src_s, dest = spec.split(":", 1)
    src = Path(src_s).resolve()
    if not src.is_file():
        raise SystemExit(f"--source SRC not found: {src}")
    if not dest.startswith("/"):
        raise SystemExit(f"--source DEST must be absolute: {dest!r}")
    return src, dest


def emit(runner_path: Path, cases_path: Path, server_cmd: str,
         sources: list[tuple[Path, str]], workdir: str,
         keep: bool) -> str:
    runner_b64 = b64(runner_path)
    cases_b64 = b64(cases_path)

    # Build per-source decode + write commands.
    src_decodes: list[str] = []
    for src, dest in sources:
        data_b64 = b64(src)
        src_decodes.append(
            f'mkdir -p "$(dirname {sh_quote(dest)})"\n'
            f'printf %s {sh_quote(data_b64)} | base64 -d > {sh_quote(dest)}'
        )
    src_block = "\n".join(src_decodes) if src_decodes else "# (no --source files)"

    cleanup = "" if keep else f'trap \'rm -rf {sh_quote(workdir)}\' EXIT\n'

    return f"""#!/usr/bin/env bash
# Generated by mcp-acceptance/scripts/remote_run.py — do not hand-edit.
set -euo pipefail
WORK={sh_quote(workdir)}
mkdir -p "$WORK"
{cleanup}
# --- runner ---
printf %s {sh_quote(runner_b64)} | base64 -d > "$WORK/mcp_acceptance.py"
chmod +x "$WORK/mcp_acceptance.py"

# --- cases ---
printf %s {sh_quote(cases_b64)} | base64 -d > "$WORK/cases.jsonl"

# --- additional source files (server.py etc.) ---
{src_block}

# --- run acceptance; exit code is the contract ---
python3 "$WORK/mcp_acceptance.py" --server {sh_quote(server_cmd)} --cases "$WORK/cases.jsonl"
"""


def sh_quote(s: str) -> str:
    """POSIX single-quote escape."""
    return "'" + s.replace("'", "'\"'\"'") + "'"


def main() -> int:
    p = argparse.ArgumentParser(description=(__doc__ or "").split("\n\n", 1)[0])
    p.add_argument("--runner", type=Path, default=DEFAULT_RUNNER,
                   help=f"path to mcp_acceptance.py (default: {DEFAULT_RUNNER})")
    p.add_argument("--cases", type=Path, required=True,
                   help="path to cases.jsonl (driver-local)")
    p.add_argument("--server-cmd", required=True,
                   help='command the slave will run, e.g. "python3 /tmp/mcpa/server.py"')
    p.add_argument("--source", action="append", default=[], metavar="SRC:DEST",
                   help="upload SRC (driver-local) to DEST (absolute slave path); "
                        "repeatable. Typical: --source generated_mcp/foo/v1.py:/tmp/mcpa/server.py")
    p.add_argument("--workdir", default="/tmp/mcpa",
                   help="absolute slave workdir for runner+cases (default /tmp/mcpa)")
    p.add_argument("--keep", action="store_true",
                   help="skip cleanup trap (leave files on slave for inspection)")
    args = p.parse_args()

    if not args.runner.is_file():
        raise SystemExit(f"--runner not found: {args.runner}")
    if not args.cases.is_file():
        raise SystemExit(f"--cases not found: {args.cases}")
    if not args.workdir.startswith("/"):
        raise SystemExit(f"--workdir must be absolute: {args.workdir!r}")

    sources = [parse_source(s) for s in args.source]
    script = emit(args.runner, args.cases, args.server_cmd, sources,
                  args.workdir, args.keep)
    sys.stdout.write(script)
    return 0


if __name__ == "__main__":
    sys.exit(main())
